# Generated by Django 4.2.16 on 2024-11-23 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_alter_line_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='line',
            name='odds',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
