# Generated by Django 4.2.16 on 2024-11-24 15:17

import bet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_alter_bet_stake_alter_line_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[bet.models.settledAmountValidator]),
        ),
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[bet.models.positiveAmountValidator]),
        ),
    ]
